apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prompt-engine.fullname" . }}-config
  labels:
    {{- include "prompt-engine.labels" . | nindent 4 }}
data:
  datasource-url: {{ .Values.config.datasourceUrl | quote }}
  ciap-jwks-uri: {{ .Values.config.ciapJwksUri | quote }}
  otel-exporter-endpoint: {{ .Values.config.otelExporterEndpoint | quote }}
  eventbus-kafka-bootstrap-servers: {{ .Values.config.eventBusKafkaBootstrapServers | quote }}
  execution-provider: {{ .Values.config.executionProvider | quote }}
  model-profile-max-context-tokens: {{ .Values.config.modelProfileMaxContextTokens | quote }}
  model-profile-tokenizer-id: {{ .Values.config.modelProfileTokenizerId | quote }}
  model-profile-cost-per-token: {{ .Values.config.modelProfileCostPerToken | quote }}
